AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AutoSpotting Customer Account Template - Forwards EC2 and AutoScaling events
  to the main AutoSpotting account's EventBridge and provides IAM role for
  cross-account AutoSpotting operations.

Parameters:
  MainAccountId:
    Type: String
    Description: The AWS Account ID where AutoSpotting is installed.
    AllowedPattern: "^[0-9]{12}$"
    ConstraintDescription: Must be a valid 12-digit AWS Account ID.
    Default: "982534352845"

  MainRegion:
    Type: String
    Description: The AWS region where AutoSpotting is installed.
    Default: ap-south-1

  AutoSpottingLambdaRoleArn:
    Type: String
    Description: >
      The ARN of the AutoSpotting Lambda execution role in the main account.
      This role will be allowed to assume the AutoSpotting role in this account.
    AllowedPattern: "^arn:aws:iam::[0-9]{12}:role/.+$"
    ConstraintDescription: Must be a valid IAM role ARN.
    Default: "arn:aws:iam::982534352845:role/lambda/autospotting-LambdaExecutionRole-QLEgqMN3g4f1"

  Regions:
    Type: CommaDelimitedList
    Description: >
      Comma-separated list of regions where to deploy the event forwarding rules.
      Events from these regions will be forwarded to the main AutoSpotting account.
      Defaults to standard AWS regions that don't require opt-in.
    Default: "ap-northeast-1,ap-northeast-2,ap-northeast-3,ap-south-1,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-north-1,eu-west-1,eu-west-2,eu-west-3,sa-east-1,us-east-1,us-east-2,us-west-1,us-west-2"

  DeployRegionalStackSet:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"
    Description: >
      Whether to deploy a StackSet for multi-region event forwarding.
      Set to false if you only want to forward events from the current region.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Main AutoSpotting Account Configuration
        Parameters:
          - MainAccountId
          - MainRegion
          - AutoSpottingLambdaRoleArn
      - Label:
          default: Regional Deployment
        Parameters:
          - Regions
          - DeployRegionalStackSet
    ParameterLabels:
      MainAccountId:
        default: Main Account ID where AutoSpotting runs
      MainRegion:
        default: Region where AutoSpotting Lambda is deployed
      AutoSpottingLambdaRoleArn:
        default: ARN of AutoSpotting Lambda execution role
      Regions:
        default: Regions to forward events from
      DeployRegionalStackSet:
        default: Deploy multi-region StackSet?

Conditions:
  DeployStackSet:
    Fn::Equals:
      - Ref: DeployRegionalStackSet
      - "true"

Resources:
  # ==========================================
  # IAM ROLES (Created once in deployment region)
  # ==========================================
  
  # IAM Role that AutoSpotting Lambda assumes to manage resources in this account
  AutoSpottingExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AutoSpotting-Execution-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AutoSpottingLambdaRoleArn
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref AWS::AccountId
      Path: /
      Policies:
        - PolicyName: AutoSpottingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AutoScalingPermissions
                Effect: Allow
                Action:
                  - "autoscaling:AttachInstances"
                  - "autoscaling:CompleteLifecycleAction"
                  - "autoscaling:CreateOrUpdateTags"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeAutoScalingInstances"
                  - "autoscaling:DescribeInstanceRefreshes"
                  - "autoscaling:DescribeLaunchConfigurations"
                  - "autoscaling:DescribeLifecycleHooks"
                  - "autoscaling:DescribeScalingActivities"
                  - "autoscaling:DescribeTags"
                  - "autoscaling:DetachInstances"
                  - "autoscaling:ResumeProcesses"
                  - "autoscaling:SetInstanceProtection"
                  - "autoscaling:SuspendProcesses"
                  - "autoscaling:TerminateInstanceInAutoScalingGroup"
                  - "autoscaling:UpdateAutoScalingGroup"
                Resource: "*"
              - Sid: EC2Permissions
                Effect: Allow
                Action:
                  - "ec2:AssociateAddress"
                  - "ec2:AttachVolume"
                  - "ec2:CreateTags"
                  - "ec2:CreateLaunchTemplate"
                  - "ec2:CreateLaunchTemplateVersion"
                  - "ec2:CreateFleet"
                  - "ec2:DeleteTags"
                  - "ec2:DeleteLaunchTemplate"
                  - "ec2:DescribeAddresses"
                  - "ec2:DescribeImages"
                  - "ec2:DescribeLaunchTemplates"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeVolumes"
                  - "ec2:DetachVolume"
                  - "ec2:DisassociateAddress"
                  - "ec2:DescribeInstanceAttribute"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeLaunchTemplateVersions"
                  - "ec2:DescribeRegions"
                  - "ec2:DescribeSpotPriceHistory"
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                Resource: "*"
              - Sid: ELBPermissions
                Effect: Allow
                Action:
                  - "elasticloadbalancing:DescribeLoadBalancers"
                  - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
                  - "elasticloadbalancing:DeregisterTargets"
                  - "elasticloadbalancing:DescribeTargetGroups"
                  - "elasticloadbalancing:DescribeTargetHealth"
                Resource: "*"
              - Sid: ECSPermissions
                Effect: Allow
                Action:
                  - "ecs:DescribeContainerInstances"
                  - "ecs:ListClusters"
                  - "ecs:ListContainerInstances"
                  - "ecs:UpdateContainerInstancesState"
                Resource: "*"
              - Sid: BeanstalkPermissions
                Effect: Allow
                Action:
                  - "elasticbeanstalk:DescribeEnvironments"
                Resource: "*"
              - Sid: CodeDeployPermissions
                Effect: Allow
                Action:
                  - "codedeploy:CreateDeployment"
                  - "codedeploy:GetApplicationRevision"
                  - "codedeploy:GetDeploymentConfig"
                  - "codedeploy:GetDeploymentGroup"
                  - "codedeploy:ListApplications"
                  - "codedeploy:ListDeploymentGroups"
                Resource: "*"
              - Sid: CloudFormationPermissions
                Effect: Allow
                Action:
                  - "cloudformation:Describe*"
                Resource: "*"
              - Sid: IAMPermissions
                Effect: Allow
                Action:
                  - "iam:CreateServiceLinkedRole"
                  - "iam:PassRole"
                Resource: "*"

  # IAM Role for EventBridge to forward events (created once globally in this account)
  EventBridgeCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AutoSpotting-EventBridge-CrossAccount-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: PutEventsToMainAccount
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource:
                  - !Sub "arn:aws:events:${MainRegion}:${MainAccountId}:event-bus/default"

  # ==========================================
  # STACKSET ADMINISTRATION ROLES
  # ==========================================
  
  StackSetAdministrationRole:
    Condition: DeployStackSet
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub "arn:${AWS::Partition}:iam::*:role/AWSCloudFormationStackSetExecutionRole"

  StackSetExecutionRole:
    Condition: DeployStackSet
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StackSetExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - events:*
                  - iam:*
                  - s3:GetObject
                Resource: "*"

  # ==========================================
  # STACKSET FOR MULTI-REGION DEPLOYMENT
  # ==========================================
  
  RegionalStackSet:
    Condition: DeployStackSet
    DependsOn:
      - StackSetAdministrationRole
      - StackSetExecutionRole
      - EventBridgeCrossAccountRole
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: AutoSpotting-CustomerRegionalResources
      Description: >
        StackSet that deploys regional event forwarding rules for AutoSpotting
        in customer accounts across all enabled regions.
      TemplateBody: !Sub |
        AWSTemplateFormatVersion: "2010-09-09"
        Description: Regional event forwarding rules for AutoSpotting customer accounts.
        
        Parameters:
          MainAccountId:
            Type: String
          MainRegion:
            Type: String
          EventBridgeCrossAccountRoleArn:
            Type: String

        Resources:
          # Event rule for Spot Instance Interruption Warnings
          SpotTerminationEventRule:
            Type: AWS::Events::Rule
            Properties:
              Name: AutoSpotting-SpotTermination-Forward
              Description: Forwards Spot termination events to main AutoSpotting account.
              EventPattern:
                detail-type:
                  - "EC2 Spot Instance Interruption Warning"
                  - "EC2 Instance Rebalance Recommendation"
                source:
                  - "aws.ec2"
              State: ENABLED
              Targets:
                - Arn: !Sub "arn:aws:events:${!MainRegion}:${!MainAccountId}:event-bus/default"
                  Id: ForwardToMainAccount
                  RoleArn: !Ref EventBridgeCrossAccountRoleArn

          # Event rule for EC2 Instance State Changes
          InstanceRunningEventRule:
            Type: AWS::Events::Rule
            Properties:
              Name: AutoSpotting-InstanceRunning-Forward
              Description: Forwards EC2 instance running events to main AutoSpotting account.
              EventPattern:
                detail-type:
                  - "EC2 Instance State-change Notification"
                source:
                  - "aws.ec2"
                detail:
                  state:
                    - "running"
              State: ENABLED
              Targets:
                - Arn: !Sub "arn:aws:events:${!MainRegion}:${!MainAccountId}:event-bus/default"
                  Id: ForwardToMainAccount
                  RoleArn: !Ref EventBridgeCrossAccountRoleArn

          # Event rule for Lifecycle Hook failures
          LifecycleHookEventRule:
            Type: AWS::Events::Rule
            Properties:
              Name: AutoSpotting-LifecycleHook-Forward
              Description: Forwards lifecycle hook events to main AutoSpotting account.
              EventPattern:
                detail-type:
                  - "AWS API Call via CloudTrail"
                source:
                  - "aws.autoscaling"
                detail:
                  eventName:
                    - "CompleteLifecycleAction"
                  errorCode:
                    - "ValidationException"
                  requestParameters:
                    lifecycleActionResult:
                      - "CONTINUE"
              State: ENABLED
              Targets:
                - Arn: !Sub "arn:aws:events:${!MainRegion}:${!MainAccountId}:event-bus/default"
                  Id: ForwardToMainAccount
                  RoleArn: !Ref EventBridgeCrossAccountRoleArn
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SELF_MANAGED
      Parameters:
        - ParameterKey: MainAccountId
          ParameterValue: !Ref MainAccountId
        - ParameterKey: MainRegion
          ParameterValue: !Ref MainRegion
        - ParameterKey: EventBridgeCrossAccountRoleArn
          ParameterValue: !GetAtt EventBridgeCrossAccountRole.Arn
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref AWS::AccountId
          Regions: !Ref Regions
      OperationPreferences:
        FailureTolerancePercentage: 50
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL

Outputs:
  AutoSpottingExecutionRoleArn:
    Description: >
      ARN of the IAM role that AutoSpotting assumes to manage resources in this account.
      Add this to your XamOps backend sync endpoint.
    Value: !GetAtt AutoSpottingExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AutoSpottingExecutionRoleArn"

  CustomerAccountId:
    Description: The AWS Account ID of this customer account
    Value: !Ref AWS::AccountId

  MainAccountId:
    Description: The main AutoSpotting account ID that receives events
    Value: !Ref MainAccountId

  ExternalId:
    Description: External ID for secure cross-account role assumption
    Value: !Ref AWS::AccountId

  DeployedRegions:
    Description: Regions where EventBridge rules are deployed
    Value: !Join [", ", !Ref Regions]

  SetupInstructions:
    Description: Instructions to complete the cross-account setup
    Value: !Sub |
      ✅ Stack deployed successfully!
      
      Next steps:
      1. Sync this account in XamOps UI using the "Sync Account" button
      2. Account ID: ${AWS::AccountId}
      3. Role ARN: ${AutoSpottingExecutionRole.Arn}
      4. External ID: ${AWS::AccountId}
      
      AutoSpotting will now discover and manage ASGs in this account.
