name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sahil-remoterepo
          password: ${{ secrets.UAT_GHCR }}

      - name: Build & Push Billops
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./billops/Dockerfile
          push: true
          tags: ghcr.io/sahil-remoterepo/billops:latest

      - name: Build & Push Xamops
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./xamops-service/Dockerfile
          push: true
          tags: ghcr.io/sahil-remoterepo/xamops-service:latest

      - name: Build & Push Service Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./service-registry/Dockerfile
          push: true
          tags: ghcr.io/sahil-remoterepo/service-registry:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend-app
          file: ./frontend-app/Dockerfile
          push: true
          tags: ghcr.io/sahil-remoterepo/frontend-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy containers on EC2
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy microservices" \
            --parameters commands='[
              "sudo docker login ghcr.io -u sahil-remoterepo -p ${{ secrets.UAT_GHCR }}",
              "sudo docker pull ghcr.io/sahil-remoterepo/billops:latest",
              "sudo docker pull ghcr.io/sahil-remoterepo/xamops-service:latest",
              "sudo docker pull ghcr.io/sahil-remoterepo/service-registry:latest",
              "sudo docker pull ghcr.io/sahil-remoterepo/frontend-app:latest",
              "sudo docker stop billops || true && sudo docker rm billops || true",
              "sudo docker stop xamops-service || true && sudo docker rm xamops-service || true",
              "sudo docker stop service-registry || true && sudo docker rm service-registry || true",
              "sudo docker stop frontend-app || true && sudo docker rm frontend-app || true",
              "sudo docker run -d --name service-registry --network xamops-network ghcr.io/sahil-remoterepo/service-registry:latest",
              "sudo docker run -d --name billops --network xamops-network ghcr.io/sahil-remoterepo/billops:latest",
              "sudo docker run -d --name xamops-service --network xamops-network --restart always -p 8080:8080 -e SPRING_PROFILES_ACTIVE=uat -e DB_HOST=172.18.0.1 -e DB_USER=app_user_uat -e DB_PASS=SecurePass123! -e DB_NAME=xamops_db_uat -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/ ghcr.io/sahil-remoterepo/xamops-service:latest",
              "sudo docker run -d --name frontend-app --network xamops-network ghcr.io/sahil-remoterepo/frontend-app:latest"
            ]'
